# Generated by Django 3.1 on 2020-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='eng',
            field=models.TextField(null=True),
        ),
    ]
