# Generated by Django 3.1 on 2020-08-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20200810_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'managed': False},
        ),
    ]
